server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc.batch_size: 1000 # Hibernate 배치 크기
        order_inserts: true   # INSERT 정렬 최적화
        order_updates: true   # UPDATE 정렬 최적화
        generate_statistics: true

  batch:
    jdbc:
      initialize-schema: always